language: python
python:
  - "3.7"
after_success:
  coveralls

dist: xenial
sudo: required

addons:
  sonarcloud:
    organization: "apecr-github"

install:
  - pip install pipenv
  - pipenv install --dev
script:
  - python -m pytest -vv --capture=tee-sys
  - npm run coverage
  - coverage run --source . -m pytest && coverage report --omit=tests/*
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'