language: python
python:
  - "3.7"
after_success:
  coveralls

dist: xenial
sudo: required

addons:
  sonarcloud:
    organization: "apecr-github"

install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run test
  - pipenv run coverage
  - pipenv run sonar

cache:
  directories:
    - '$HOME/.sonar/cache'