language: python
python:
  - "3.7"
after_success:
  coveralls

addons:
  sonarcloud:
    organization: "apecr-github"
jdk:
  - oraclejdk8

install:
  - pip install pipenv
  - pipenv install --dev
script:
  - python -m pytest -vv --capture=tee-sys
  - coverage run --source . -m pytest
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'